### ISSUE TITLE
error: 'path' is unavailable: introduced in macOS 10.15

### ISSUE THREAD

**Issue by aogriffiths** [Xaymar/obs-StreamFX#316]
### Description

I followed the instructions at [wiki/Building-From-Source](https://github.com/Xaymar/obs-StreamFX/wiki/Building-From-Source) but got the following build error:

```
[88%] Building CXX object UI/frontend-plugins/streamfx/CMakeFiles/StreamFX.dir/generated/mocs_compilation.cpp.o
In file included from ./obs-studio/build/UI/frontend-plugins/streamfx/generated/mocs_compilation.cpp:2:
In file included from ./obs-studio/build/UI/frontend-plugins/streamfx/generated/HDSICPREIZ/moc_ui-about-entry.cpp:10:
In file included from ./obs-studio/UI/frontend-plugins/streamfx/source/ui/ui-about-entry.hpp:22:
In file included from ./obs-studio/UI/frontend-plugins/streamfx/source/ui/ui-about.hpp:21:
In file included from ./obs-studio/UI/frontend-plugins/streamfx/source/common.hpp:50:
./obs-studio/UI/frontend-plugins/streamfx/source/util/util-library.hpp:31:28: error: 'path' is unavailable: introduced in
      macOS 10.15
                library(std::filesystem::path file);
                                         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/filesystem:739:24: note: 'path' has been explicitly marked unavailable
      here
class _LIBCPP_TYPE_VIS path {
```

I've googled the problem and people have solved a similar problem for other projects but I can't work out how to solve it for SteamFX.

Your help would be very much approciated!

### System Information

- Software Version: cloned today (so 778fc7f I guess)
- Operating System: macOS 10.15.5 (19F101)
- Kernel Version: Darwin 19.5.0
- CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
- GPU:  Intel Iris Plus Graphics 655
- RAM: 8 GB

**Comment by aogriffiths** [comment]
I may have found a solution.

When following the instructions here [obs-studio/wiki/Install-Instructions](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions). Change the line:

```
cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DDISABLE_PYTHON=ON ..
```

to

```
cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DDISABLE_PYTHON=ON ..
```

**Comment by Xaymar** [comment]
This looks like the compiler used doesn't fully support C++17, which is the minimum C++ version necessary to build the plugin.

**Comment by mtrpires** [comment]
> I may have found a solution.
> 
> When following the instructions here [obs-studio/wiki/Install-Instructions](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions). Change the line:
> 
> ```
> cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DDISABLE_PYTHON=ON ..
> ```
> 
> to
> 
> ```
> cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DDISABLE_PYTHON=ON ..
> ```

this helped conclude the building OBS from source, but the plugin didn't get compiled -- what fixed for me was:

```brew install gcc --HEAD```

then follow build instructions, adding the ```-std=c++17``` flag to cmake: https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions:

```cmake -std=c++17 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DDISABLE_PYTHON=ON ..```

StreamFX works on macOS 10.15.5!

<img width="973" alt="Screen Shot 2020-08-26 at 21 07 13" src="https://user-images.githubusercontent.com/835712/91368697-9f431e80-e7be-11ea-8367-abf06ec8d3ad.png">

**Comment by migeru-san** [comment]
@mtrpires Hi Pires! great stuff putting to this togther for Mac, can you explain how to install it on OBS Studio for Mac? I am not. Coder.

**Comment by mtrpires** [comment]
> @mtrpires Hi Pires! great stuff putting to this togther for Mac, can you explain how to install it on OBS Studio for Mac? I am not. Coder.

hi @migeru-san, your question is off-topic. StreamFX needs to be built for the mac with OBS Studio, from source. If you don't know what that means you should try and learn. Beyond what I posted I won't be able to guide you. [Here's a good place to start](https://ed.com/source-install-macos/). After that, read the [building instructions](https://github.com/Xaymar/obs-StreamFX/wiki/Building-From-Source).

**Comment by Xaymar** [comment]
Is this still happening in current master?

**Comment by ardnaxelarak** [comment]
> Is this still happening in current master?

Yes.

The workaround to change `-DCMAKE_OSX_DEPLOYMENT_TARGET` to `10.15` seems to mostly work for me, but I ultimately ran into some other (non-breaking) issues which may or may not be related.
(I'm going to file them as new issues in a bit once I can get some more information.)

**Comment by Xaymar** [comment]
Might need to document this in the instructions then. The project requires full C++17 support, so if a compiler doesn't support it by default, adjustments need to be made. I don't think I can fix this with just at-configure overrides which are used to improve/fix compilation results, especially since I am setting the CXX version in the code.

**Comment by Xaymar** [comment]
I've added a reference to this issue on the Building From Source page, which will hopefully help future readers of the guide. Unfortunately this is outside of my control, as the project requires C++17 and actually does set it as the required standard for all created targets. [This seems to be ignored by CMake on Mac, since it seems that the Mac toolchains are weird.](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html)

**Comment by justingwl** [comment]
> > I may have found a solution.
> > When following the instructions here [obs-studio/wiki/Install-Instructions](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions). Change the line:
> > ```
> > cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DDISABLE_PYTHON=ON ..
> > ```
> > 
> > 
> > to
> > ```
> > cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DDISABLE_PYTHON=ON ..
> > ```
> 
> this helped conclude the building OBS from source, but the plugin didn't get compiled -- what fixed for me was to follow build instructions, adding the `-std=c++17` flag to cmake: https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions:
> 
> `cmake -std=c++17 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DDISABLE_PYTHON=ON ..`
> 
> then `make`
> 
> The binary will be in `obs-studio/build/rundir/RelWithDebInfo/bin` and you'll be able to execute it with `./obs`
> 
> StreamFX works on macOS 10.15.5!
> 
> <img alt="Screen Shot 2020-08-26 at 21 07 13" width="973" src="https://user-images.githubusercontent.com/835712/91368697-9f431e80-e7be-11ea-8367-abf06ec8d3ad.png">
> 
> This will work if you're not using the `full-build-macos.sh` script but rather going over the building steps manually. Curiously, the `full-build-macosx.sh` script targets macOS `10.11` / `10.13` and `c++11`. I needed to edit the file in certain locations to refer to `10.15` / `c++17` to make it work with the default build instructions. Because of these changes I was able to build an **unsigned** `.dmg` and app bundle with `./CI/full-build-macos.sh -b -p`.
> 
> You can download the `.dmg` bundle and try it for yourself [here](https://drive.google.com/file/d/13jXtTWK5gwY262nPt7dficjF8i5P2hnk/view?usp=sharing). It will work only on macOS 10.15 though. DMG is unsigned, use it at your own risk (right click on the `.app` bundle, command+left click to open).

I tweaked a few all references of `10.11` / `c++13` to `10.13` and `c++11` in the `full-build-macosx.sh` script, but I am receiving the error:

> obs-studio/plugins/streamfx/source/encoders/handlers/amf_shared.cpp:120:23: error: 
      use of undeclared identifier 'lib_name'
                util::library::load(lib_name);

After looking into the code, `lib_name` does not get assigned  a value since I'm running OS X.

**Comment by Xaymar** [comment]
See other: #400
